apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-production-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-production
  template:
    metadata:
      labels:
        app: myapp-production
    spec:
      containers:
        - name: myapp
          image: syednadeembe/myflaskapp:prod
          resources:
            requests:
               memory: "100Mi"
               cpu: "100m"
            limits:
               memory: "100Mi"
               cpu: "100m"
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-production-service
spec:
  selector:
    app: myapp-production
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-production-nodeport
spec:
  selector:
    app: myapp-production
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090  # optional: specify or let K8s auto-assign from 30000–32767

