apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-production-deployment
  labels:
    app: myapp-production
spec:
  selector:
    matchLabels:
      app: myapp-production
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp-production
    spec:
      containers:
      - name: myapp-production
        image: syednadeembe/myflaskapp:prod
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 10m
          requests:
            cpu: 10m
